import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card/Card'
import Envelope from '../components/Envelope'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.home_container}>
                <Card />
            </div>
        </div>
    )
}
